use_frameworks!

target 'estgames-common-framework_Example' do
    pod 'AWSAuthCore', '~> 2.6.1'
    pod 'AWSPinpoint', '~> 2.6.1'
    pod 'AWSGoogleSignIn', '~> 2.6.1'
    pod 'GoogleSignIn', '~> 4.0.0'
    pod 'AWSFacebookSignIn', '~> 2.6.1'
    pod 'AWSCognito', '~> 2.6.1'
    pod 'AWSAuthUI', '~> 2.6.1'
    pod 'Alamofire', '~> 4.7'
    #pod 'SwiftKeychainWrapper'
    
    pod 'estgames-common-framework', :path => '../'
    #pod 'estgames-common-framework', '~> 0.7.0'






  target 'estgames-common-framework_Tests' do
    inherit! :search_paths
    
  end
end
