use_frameworks!

target 'pod_gitlab_test_Example' do
    pod 'Alamofire', '~> 4.5'
    #pod 'pod_gitlab_test', '~> 0.2.0'
  pod 'pod_gitlab_test', :path => '../'

  target 'pod_gitlab_test_Tests' do
    inherit! :search_paths

    
  end
end
