# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'estgames-common-framework-example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleSignIn', '~> 4.0.0'
  pod 'estgames-common-framework', :path => '../'
  # Pods for estgames-common-framework-example

end
